name: hq_monitoring

x-logging: &logging
  logging:
    driver: loki
    options:
      loki-url: http://10.5.0.2:3100/loki/api/v1/push
      loki-retries: "5"
      loki-batch-size: "100"

services:
  # nginx:
  #   image: nginx@sha256:516475cc129da42866742567714ddc681e5eed7b9ee0b9e9c015e464b4221a00
  #   <<: *logging
  #   volumes:
  #   - ./conf/nginx.conf:/etc/nginx/nginx.conf
  #   - ./ssl:/etc/nginx/ssl
  #   ports:
  #   - "80:80"
  #   - "443:443"
  #   depends_on:
  #   - grafana
  #   networks:
  #     vpcbr:
  #       ipv4_address: 10.5.0.3

  loki:
    image: grafana/loki@sha256:8b5bd7748d0e4da66cd741ac276e485517514af0bea32167e27c0e1a95bcf8aa
    ports:
      - 127.0.0.1:3100:3100
    networks:
      vpcbr:
        ipv4_address: 10.5.0.2

  prometheus:
    image: prom/prometheus:latest
    ports:
    - 127.0.0.1:9090:9090
    # volumes:
    # - ./conf/prometheus.yml:/etc/prometheus/prometheus.yml
    # - ./conf/alert_rules.yml:/etc/prometheus/alert_rules.yml
    networks:
      vpcbr:
        ipv4_address: 10.5.0.4

  alertmanager:
    image: prom/alertmanager:latest
    ports:
    - 127.0.0.1:9093:9093
    # volumes:
    # - ./conf/alertmanager.yml:/etc/alertmanager/alertmanager.yml
    networks:
      vpcbr:
        ipv4_address: 10.5.0.6
  
  tempo:
    image: grafana/tempo:latest
    ports:
    - 127.0.0.1:3200:3200
    networks:
      vpcbr:
        ipv4_address: 10.5.0.7

  grafana:
    image: grafana/grafana@sha256:0dc5a246ab16bb2c38a349fb588174e832b4c6c2db0981d0c3e6cd774ba66a54
    <<: *logging
    environment:
    - GF_SECURITY_ADMIN_PASSWORD=loki@aljf
    volumes:
    - ./conf/grafana/provisioning/:/etc/grafana/provisioning/
    depends_on:
    - loki
    - prometheus
    ports:
      - 127.0.0.1:3000:3000
    networks:
      vpcbr:
        ipv4_address: 10.5.0.5

networks:
  vpcbr:
    name: vpcbr
    driver: bridge
    ipam:
     config:
       - subnet: 10.5.0.0/16
         gateway: 10.5.0.1
