apiVersion: 1

datasources:
  - name: Loki
    type: loki
    access: proxy
    url: http://10.5.0.2:3100
    isDefault: true
    jsonData:
      maxLines: 1000

  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://10.5.0.4:9090
    isDefault: false
 